backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dxpw333bo  # À remplacer par ton nom Cloudinary
    api_key: 948742952497674        # À remplacer par ta clé API Cloudinary

publish_mode: editorial_workflow

collections:
  - name: "chats"
    label: "Chats adultes"
    folder: "_chats"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Âge", name: "age", widget: "string", hint: "Ex: 2 ans, 6 mois..." }
      - { label: "Sexe", name: "sexe", widget: "select", options: ["Mâle", "Femelle"] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Est adopté ?", name: "adopte", widget: "boolean", default: false }

  - name: "chatons"
    label: "Chatons"
    folder: "_chatons"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Âge", name: "age", widget: "string", hint: "Ex: 3 mois, 8 semaines..." }
      - { label: "Sexe", name: "sexe", widget: "select", options: ["Mâle", "Femelle"] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Est adopté ?", name: "adopte", widget: "boolean", default: false }
